// Code generated by "stringer -type=PartyAction"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PartyActionJoin-0]
	_ = x[PartyActionLeave-1]
	_ = x[PartySelfLeave-2]
}

const _PartyAction_name = "PartyActionJoinPartyActionLeavePartySelfLeave"

var _PartyAction_index = [...]uint8{0, 15, 31, 45}

func (i PartyAction) String() string {
	if i < 0 || i >= PartyAction(len(_PartyAction_index)-1) {
		return "PartyAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PartyAction_name[_PartyAction_index[i]:_PartyAction_index[i+1]]
}
