package enums

//go:generate golang.org/x/tools/cmd/stringer -type=EventType
type EventType int16

const (
	EventTypeUnused EventType = iota
	EventTypeLeave
	EventTypeJoinFinished //  <- UserInfo
	EventTypeMove
	EventTypeTeleport
	EventTypeChangeEquipment
	EventTypeHealthUpdate
	EventTypeHealthUpdates
	EventTypeEnergyUpdate
	EventTypeDamageShieldUpdate
	EventTypeCraftingFocusUpdate
	EventTypeActiveSpellEffectsUpdate
	EventTypeResetCooldowns
	EventTypeAttack
	EventTypeCastStart
	EventTypeChannelingUpdate
	EventTypeCastCancel
	EventTypeCastTimeUpdate
	EventTypeCastFinished
	EventTypeCastSpell
	EventTypeCastSpells
	EventTypeCastHit
	EventTypeCastHits
	EventTypeStoredTargetsUpdate
	EventTypeChannelingEnded
	EventTypeAttackBuilding
	EventTypeInventoryPutItem    //   map[0:652 1:6 2:[118 -97 114 112 -46 84 -60 75 -103 -93 -3 -29 118 -125 -50 96] 3:17 252:23] (0: ObjectId, 1: Inventory slot (no value is slot 0), 2: InteractGuid)
	EventTypeInventoryDeleteItem //  map[0:754 1:48 252:24] (0: ObjectId)
	EventTypeInventoryState
	EventTypeNewCharacter
	EventTypeNewEquipmentItem //   map[0:657 1:2036 2:1 4:28169331 5:Apolo540 6:3 7:90000000 8:[] 9:[0] 252:27] (0: ObjectId, 1: ItemId, 2: Amount, 4: Est. market value, 5: CrafterName)
	EventTypeNewSiegeBannerItem
	EventTypeNewSimpleItem //   map[0:505 1:7006 2:1 3:true 4:29033970 252:27] (0: ObjectId, 1: ItemId, 2: Amount, 4: Est. market value)
	EventTypeNewFurnitureItem
	EventTypeNewKillTrophyItem
	EventTypeNewJournalItem
	EventTypeNewLaborerItem //  [0:513 1:7996 2:4 4:522947156 5: 6:10000 7:72000000 252:32]
	EventTypeNewEquipmentItemLegendarySoul
	EventTypeNewSimpleHarvestableObject
	EventTypeNewSimpleHarvestableObjectList
	EventTypeNewHarvestableObject //  map[0:[3405 3468] 1:[6 6] 2:[3 2] 3:[182 -383 176 -369 183 -371] 4:[3 3] 252:35] - 0: ObjectId 2: Max charges, 4: Current charges
	EventTypeNewTreasureDestinationObject
	EventTypeTreasureDestinationObjectStatus
	EventTypeCloseTreasureDestinationObject
	EventTypeNewSilverObject
	EventTypeNewBuilding
	EventTypeHarvestableChangeState
	EventTypeMobChangeState
	EventTypeFactionBuildingInfo
	EventTypeCraftBuildingInfo
	EventTypeRepairBuildingInfo
	EventTypeMeldBuildingInfo
	EventTypeConstructionSiteInfo
	EventTypePlayerBuildingInfo
	EventTypeFarmBuildingInfo
	EventTypeTutorialBuildingInfo
	EventTypeLaborerObjectInfo
	EventTypeLaborerObjectJobInfo
	EventTypeMarketPlaceBuildingInfo
	EventTypeHarvestStart //  map[0:5270 1:637926215956544319 2:637926215956544319 3:4250 4:16 5:1.6169999 6:5287 7:2195 252:52] - 0 = UserId, 3 = ObjectId, 5: Abbauzeit 7: Abbau-Tool (T8_2H_TOOL_SICKLE),
	EventTypeHarvestCancel
	EventTypeHarvestFinished //  map[0:5270 1:637926215956544319 2:637926215972723131 3:4250 4:1 5:1 7:28 8:[] 9:[] 252:54] - 0: UserId, 3: ObjectId, 4:ItemId 5: Res Standard Quantity 6: Sammelbonus Res, 6: Premium Bonus Res, 8: Inhalt in der Ressource
	EventTypeTakeSilver      //  map[0:-57 1:2178162 2:-57 3:10000000 8:10000 252:55]
	EventTypeRemoveSilver
	EventTypeActionOnBuildingStart
	EventTypeActionOnBuildingCancel
	EventTypeActionOnBuildingFinished //  Repear: [60]evInstallResourceCancel - map[0:1562 1:63802829 282167 2:442 3:454 4:2 252:60] 0: UserObjectId, 2: ActionId, 4: ActionType
	EventTypeItemRerollQualityFinished
	EventTypeInstallResourceStart
	EventTypeInstallResourceCancel
	EventTypeInstallResourceFinished
	EventTypeCraftItemFinished
	EventTypeLogoutCancel
	EventTypeChatMessage
	EventTypeChatSay
	EventTypeChatWhisper
	EventTypeChatMuted
	EventTypePlayEmote
	EventTypeStopEmote
	EventTypeSystemMessage
	EventTypeUtilityTextMessage
	EventTypeUpdateMoney //  map[0:4195 1:884995625105 252:71] (0: ObjectId, 1: CurrentSilver)
	EventTypeUpdateFame  //  map[0:4195 1:5811910006347 2:100000000 4:10000 6:1 7:427 252:72] (0: ObjectId, 1: TotalPlayerFame, 2: fameWithZoneMultiplier, 3: GroupSize, 4: Multiplier, 5: IsPremiumBonus, 6: BonusFactor, 8: UsedBagInsightItemIndex, 10: SatchelFame, )
	EventTypeUpdateLearningPoints
	EventTypeUpdateReSpecPoints //  map[0:[0 55814284204 0 0 0] 1:1 2:9948534 3:10000000 252:78] 2: GainedReSpec, 3: PaidSilver
	EventTypeUpdateCurrency
	EventTypeUpdateFactionStanding
	EventTypeUpdateStanding //  map[0:11575080 1:3858360 2:970279167 252:81] 0: StandingPoints
	EventTypeRespawn
	EventTypeServerDebugLog
	EventTypeCharacterEquipmentChanged //  map[0:297 1:26283117 2:[0 1721 0 0 0 2330 2301 2468 0 0] 5:[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 3168] 252:85]
	EventTypeRegenerationHealthChanged
	EventTypeRegenerationEnergyChanged
	EventTypeRegenerationMountHealthChanged
	EventTypeRegenerationCraftingChanged
	EventTypeRegenerationHealthEnergyComboChanged
	EventTypeRegenerationPlayerComboChanged
	EventTypeDurabilityChanged
	EventTypeNewLoot //  map[0:1863 2:1853 3:Dicky 4:[236.79169 -185.40233] 5:42.864536 6:true 7:1 10:[[-85 -58 82 55 101 -15 76 79 -103 -113 -21 8 -33 46 -99 -28]]
	// 12:637993823308929158 18:[] 19:[-63 68 12 104 -29 1 114 78 -91 -75 -21 68 -13 -96 -29 -67] 20:[-23 20 93 -6 73 127 19 78 -65 44 -42 65 -97 105 -82 -16] 21:25900 22:0 23:3 24:-1 252:89]
	EventTypeAttachItemContainer //   map[0:78 1:[-99 -50 125 -49 86 0 -115 74 -74 67 9 101 -87 -71 -66 -10] 3:[0 0 0 0 0 0 656 657] 4:8 252:89] (0: ObjectId, 3: ItemId[])
	EventTypeDetachItemContainer //   map[0:[-95 72 -77 -75 -70 34 127 73 -114 -96 28 8 75 -107 -106 125] 252:90]
	EventTypeInvalidateItemContainer
	EventTypeLockItemContainer
	EventTypeGuildUpdate
	EventTypeGuildPlayerUpdated
	EventTypeInvitedToGuild
	EventTypeGuildMemberWorldUpdate
	EventTypeUpdateMatchDetails
	EventTypeObjectEvent
	EventTypeNewMonolithObject
	EventTypeMonolithHasBannersPlacedUpdate
	EventTypeNewOrbObject
	EventTypeNewCastleObject
	EventTypeNewSpellEffectArea
	EventTypeUpdateSpellEffectArea
	EventTypeNewChainSpell
	EventTypeUpdateChainSpell
	EventTypeNewTreasureChest
	EventTypeStartMatch
	EventTypeStartArenaMatchInfos
	EventTypeEndArenaMatch
	EventTypeMatchUpdate
	EventTypeActiveMatchUpdate
	EventTypeNewMob
	EventTypeDebugAggroInfo
	EventTypeDebugVariablesInfo
	EventTypeDebugReputationInfo
	EventTypeDebugDiminishingReturnInfo
	EventTypeDebugSmartClusterQueueInfo
	EventTypeClaimOrbStart
	EventTypeClaimOrbFinished
	EventTypeClaimOrbCancel
	EventTypeOrbUpdate
	EventTypeOrbClaimed
	EventTypeOrbReset
	EventTypeNewWarCampObject
	EventTypeNewMatchLootChestObject
	EventTypeNewArenaExit
	EventTypeGuildMemberTerritoryUpdate
	EventTypeInvitedMercenaryToMatch
	EventTypeClusterInfoUpdate
	EventTypeForcedMovement
	EventTypeForcedMovementCancel
	EventTypeCharacterStats
	EventTypeCharacterStatsKillHistory
	EventTypeCharacterStatsDeathHistory
	EventTypeCharacterStatsKnockDownHistory
	EventTypeCharacterStatsKnockedDownHistory
	EventTypeGuildStats
	EventTypeKillHistoryDetails
	EventTypeItemKillHistoryDetails
	EventTypeFullAchievementInfo
	EventTypeFinishedAchievement
	EventTypeAchievementProgressInfo
	EventTypeFullAchievementProgressInfo
	EventTypeFullTrackedAchievementInfo
	EventTypeFullAutoLearnAchievementInfo
	EventTypeQuestGiverQuestOffered
	EventTypeQuestGiverDebugInfo
	EventTypeConsoleEvent
	EventTypeTimeSync
	EventTypeChangeAvatar
	EventTypeChangeMountSkin
	EventTypeGameEvent
	EventTypeKilledPlayer
	EventTypeDied
	EventTypeKnockedDown
	EventTypeUnconcious
	EventTypeMatchPlayerJoinedEvent
	EventTypeMatchPlayerStatsEvent
	EventTypeMatchPlayerStatsCompleteEvent
	EventTypeMatchTimeLineEventEvent
	EventTypeMatchPlayerMainGearStatsEvent
	EventTypeMatchPlayerChangedAvatarEvent
	EventTypeInvitationPlayerTrade
	EventTypePlayerTradeStart
	EventTypePlayerTradeCancel
	EventTypePlayerTradeUpdate
	EventTypePlayerTradeFinished
	EventTypePlayerTradeAcceptChange
	EventTypeMiniMapPing
	EventTypeMarketPlaceNotification
	EventTypeDuellingChallengePlayer
	EventTypeNewDuellingPost
	EventTypeDuelStarted
	EventTypeDuelEnded
	EventTypeDuelDenied
	EventTypeDuelRequestCanceled
	EventTypeDuelLeftArea
	EventTypeDuelReEnteredArea
	EventTypeNewRealEstate
	EventTypeMiniMapOwnedBuildingsPositions
	EventTypeRealEstateListUpdate
	EventTypeGuildLogoUpdate
	EventTypeGuildLogoChanged
	EventTypePlaceableObjectPlace
	EventTypePlaceableObjectPlaceCancel
	EventTypeFurnitureObjectBuffProviderInfo
	EventTypeFurnitureObjectCheatProviderInfo
	EventTypeFarmableObjectInfo
	EventTypeNewUnreadMails
	EventTypeMailOperationPossible
	EventTypeGuildLogoObjectUpdate
	EventTypeStartLogout
	EventTypeNewChatChannels
	EventTypeJoinedChatChannel
	EventTypeLeftChatChannel
	EventTypeRemovedChatChannel
	EventTypeAccessStatus
	EventTypeMounted
	EventTypeMountStart
	EventTypeMountCancel
	EventTypeNewTravelpoint
	EventTypeNewIslandAccessPoint
	EventTypeNewExit
	EventTypeUpdateHome
	EventTypeUpdateChatSettings
	EventTypeResurrectionOffer
	EventTypeResurrectionReply
	EventTypeLootEquipmentChanged
	EventTypeUpdateUnlockedGuildLogos
	EventTypeUpdateUnlockedAvatars
	EventTypeUpdateUnlockedAvatarRings
	EventTypeUpdateUnlockedBuildings
	EventTypeNewIslandManagement
	EventTypeNewTeleportStone
	EventTypeCloak
	EventTypePartyInvitation
	EventTypePartyJoinRequest
	EventTypePartyJoined       //  map[0:14368 2:1 3:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 4:[[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] [-118 61 -70 72 17 -107 121 72 -102 110 20 -25 64 20 106 2]] 5:[Triky313 Bruno313] 6:[0 0] 7:[18 0] 8:[35 0] 9:[-1 -1] 10:[true true] 252:212]
	EventTypePartyDisbanded    //  map[1:14184 252:213]
	EventTypePartyPlayerJoined //  map[0:11925 1:[-63 -19 39 16 26 35 -25 67 -111 60 -87 -58 -31 -100 -124 -44] 2:Mitch77 3:1 4:20 5:12 6:-1 7:true 252:214]
	EventTypePartyChangedOrder
	EventTypePartyPlayerLeft               //  map[0:14368 1:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 252:216]
	EventTypePartyLeaderChanged            //  map[0:14595 1:[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101] 252:217]
	EventTypePartyLootSettingChangedPlayer //  map[0:14368 1:1 252:218]
	EventTypePartySilverGained
	EventTypePartyPlayerUpdated //  map[0:Bruno313 1:true 3:5 252:221]
	EventTypePartyInvitationAnswer
	EventTypePartyJoinRequestAnswer
	EventTypePartyMarkedObjectsUpdated
	EventTypePartyOnClusterPartyJoined
	EventTypePartySetRoleFlag //  map[0:8 1:[-118 61 -70 72 17 -107 121 72 -102 110 20 -25 64 20 106 2] 252:225] (0: FlagType, 1: ObjectId)
	EventTypePartyInviteOrJoinPlayerEquipmentInfo
	EventTypePartyReadyCheckUpdate
	EventTypeSpellCooldownUpdate
	EventTypeNewHellgateExitPortal
	EventTypeNewExpeditionExit
	EventTypeNewExpeditionNarrator
	EventTypeExitEnterStart
	EventTypeExitEnterCancel
	EventTypeExitEnterFinished
	EventTypeNewQuestGiverObject
	EventTypeFullQuestInfo
	EventTypeQuestProgressInfo
	EventTypeQuestGiverInfoForPlayer
	EventTypeFullExpeditionInfo
	EventTypeExpeditionQuestProgressInfo
	EventTypeInvitedToExpedition
	EventTypeExpeditionRegistrationInfo
	EventTypeEnteringExpeditionStart
	EventTypeEnteringExpeditionCancel
	EventTypeRewardGranted
	EventTypeArenaRegistrationInfo
	EventTypeEnteringArenaStart
	EventTypeEnteringArenaCancel
	EventTypeEnteringArenaLockStart
	EventTypeEnteringArenaLockCancel
	EventTypeInvitedToArenaMatch
	EventTypeUsingHellgateShrine
	EventTypeEnteringHellgateLockStart
	EventTypeEnteringHellgateLockCancel
	EventTypePlayerCounts
	EventTypeInCombatStateUpdate //  map[0:671362 1:true 2:true 252:257] | 1 = true; player hits enemy | 2 = true; enemy hits player
	EventTypeOtherGrabbedLoot    //  LOOT: map[0:424 1:Triky313 2:Bruno313 4:1841 5:1 252:256] | SILVER: map[0:6436 2:Triky313 3:true 5:1550115 252:256] (0: ObjectId, 1: LootedBody, 2: Looter, 4: ItemId, 5: Quantity)
	EventTypeTreasureChestUsingStart
	EventTypeTreasureChestUsingFinished
	EventTypeTreasureChestUsingCancel
	EventTypeTreasureChestUsingOpeningComplete
	EventTypeTreasureChestForceCloseInventory
	EventTypeLocalTreasuresUpdate
	EventTypeLootChestSpawnpointsUpdate
	EventTypePremiumChanged
	EventTypePremiumExtended
	EventTypePremiumLifeTimeRewardGained
	EventTypeGoldPurchased
	EventTypeLaborerGotUpgraded
	EventTypeJournalGotFull
	EventTypeJournalFillError
	EventTypeFriendRequest
	EventTypeFriendRequestInfos
	EventTypeFriendInfos
	EventTypeFriendRequestAnswered
	EventTypeFriendOnlineStatus
	EventTypeFriendRequestCanceled
	EventTypeFriendRemoved
	EventTypeFriendUpdated
	EventTypePartyLootItems
	EventTypePartyLootItemsRemoved
	EventTypeReputationUpdate
	EventTypeDefenseUnitAttackBegin
	EventTypeDefenseUnitAttackEnd
	EventTypeDefenseUnitAttackDamage
	EventTypeUnrestrictedPvpZoneUpdate
	EventTypeUnrestrictedPvpZoneStatus
	EventTypeReputationImplicationUpdate
	EventTypeNewMountObject
	EventTypeMountHealthUpdate
	EventTypeMountCooldownUpdate
	EventTypeNewExpeditionAgent
	EventTypeNewExpeditionCheckPoint
	EventTypeExpeditionStartEvent
	EventTypeVoteEvent
	EventTypeRatingEvent
	EventTypeNewArenaAgent
	EventTypeBoostFarmable
	EventTypeUseFunction
	EventTypeNewPortalEntrance
	EventTypeNewPortalExit
	EventTypeNewRandomDungeonExit
	EventTypeWaitingQueueUpdate
	EventTypePlayerMovementRateUpdate
	EventTypeObserveStart
	EventTypeMinimapZergs
	EventTypeMinimapSmartClusterZergs
	EventTypePaymentTransactions
	EventTypePerformanceStatsUpdate
	EventTypeOverloadModeUpdate
	EventTypeDebugDrawEvent
	EventTypeRecordCameraMove
	EventTypeRecordStart
	EventTypeClaimPowerCrystalStart
	EventTypeClaimPowerCrystalCancel
	EventTypeClaimPowerCrystalReset
	EventTypeClaimPowerCrystalFinished
	EventTypeTerritoryClaimStart
	EventTypeTerritoryClaimCancel
	EventTypeTerritoryClaimFinished
	EventTypeTerritoryScheduleResult
	EventTypeTerritoryUpgradeWithPowerCrystalResult
	EventTypeReturningPowerCrystalStart
	EventTypeReturningPowerCrystalFinished
	EventTypeUpdateAccountState
	EventTypeStartDeterministicRoam
	EventTypeGuildFullAccessTagsUpdated
	EventTypeGuildAccessTagUpdated
	EventTypeGvgSeasonUpdate
	EventTypeGvgSeasonCheatCommand
	EventTypeSeasonPointsByKillingBooster
	EventTypeFishingStart
	EventTypeFishingCast
	EventTypeFishingCatch
	EventTypeFishingFinished
	EventTypeFishingCancel
	EventTypeNewFloatObject
	EventTypeNewFishingZoneObject
	EventTypeFishingMiniGame
	EventTypeSteamAchievementCompleted
	EventTypeUpdatePuppet
	EventTypeChangeFlaggingFinished
	EventTypeNewOutpostObject
	EventTypeOutpostUpdate
	EventTypeOutpostClaimed
	EventTypeOverChargeEnd
	EventTypeOverChargeStatus
	EventTypePartyFinderFullUpdate
	EventTypePartyFinderUpdate
	EventTypePartyFinderApplicantsUpdate
	EventTypePartyFinderEquipmentSnapshot
	EventTypePartyFinderJoinRequestDeclined
	EventTypeNewUnlockedPersonalSeasonRewards
	EventTypePersonalSeasonPointsGained
	EventTypePersonalSeasonPastSeasonDataEvent
	EventTypeEasyAntiCheatMessageToClient
	EventTypeMatchLootChestOpeningStart
	EventTypeMatchLootChestOpeningFinished
	EventTypeMatchLootChestOpeningCancel
	EventTypeNotifyCrystalMatchReward
	EventTypeCrystalRealmFeedback
	EventTypeNewLocationMarker
	EventTypeNewTutorialBlocker
	EventTypeNewTileSwitch
	EventTypeNewInformationProvider
	EventTypeNewDynamicGuildLogo
	EventTypeNewDecoration
	EventTypeTutorialUpdate
	EventTypeTriggerHintBox
	EventTypeRandomDungeonPositionInfo
	EventTypeNewLootChest    //  map[0:23 1:[20.5 177.5] 2:423 3:KEEPER_SOLO_BOOKCHEST_STANDARD 4:FOREST_GREEN_LOOTCHEST_KEEPER_SOLO_BOOKCHEST_STANDARD 5:4 6:637734315213820408 7:[] 8:[] 13:true 252:367] // map[0:4399 1:[165 -263] 3:TREASURE_SOLO_UNCOMMON 4:SWAMP_DEAD_LOOTCHEST_TREASURE_SOLO_UNCOMMON 5:4 6:637926439332719127 7:[] 8:[] 13:true 14:SWAMP_DEAD_TREASURE_SOLO 16:31ff503a-ded6-53d6-974a-7e32e3126457 252:370]
	EventTypeUpdateLootChest //  0=ObjectId, 3=PlayerGuid, 4=PlayerGuid, 7=Free4All map[0:4769 1:5 2:637927794424868192 3:[[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101]] 4:[[-45 -35 124 14 -23 103 -41 74 -71 66 67 20 -12 60 44 -101]] 6:true 7:true 8:2.6 9:true 252:371]
	EventTypeLootChestOpened //  map[0:23 252:369]
	EventTypeUpdateLootProtectedByMobsWithMinimapDisplay
	EventTypeNewShrine    //  map[0:19 1:[-89 90] 2:180 3:GENERAL_SHRINE_COMBAT_BUFF 4:SHRINE_NON_COMBAT_BUFF 5:1 6:637734312344532502 252:371]
	EventTypeUpdateShrine //  map[0:19 1:2 2:637734313445294913 252:372]
	EventTypeUpdateRoom
	EventTypeNewMistDungeonRoomMobSoul
	EventTypeNewHellgateShrine
	EventTypeUpdateHellgateShrine
	EventTypeActivateHellgateExit
	EventTypeMutePlayerUpdate
	EventTypeShopTileUpdate
	EventTypeShopUpdate
	EventTypeEasyAntiCheatKick
	EventTypeBattlEyeServerMessage
	EventTypeUnlockVanityUnlock
	EventTypeAvatarUnlocked
	EventTypeCustomizationChanged
	EventTypeBaseVaultInfo
	EventTypeGuildVaultInfo
	EventTypeBankVaultInfo //  map[0:6 1:6466931c-65a1-4c5d-870b-8724cf2611dc@3007 2:[] 3:[] 4:[] 5:[] 6:[] 7:[] 8:[] 252:390]
	EventTypeRecoveryVaultPlayerInfo
	EventTypeRecoveryVaultGuildInfo
	EventTypeUpdateWardrobe
	EventTypeCastlePhaseChanged
	EventTypeGuildAccountLogEvent
	EventTypeNewHideoutObject
	EventTypeNewHideoutManagement
	EventTypeNewHideoutExit
	EventTypeInitHideoutAttackStart
	EventTypeInitHideoutAttackCancel
	EventTypeInitHideoutAttackFinished
	EventTypeHideoutManagementUpdate
	EventTypeHideoutUpgradeWithPowerCrystalResult
	EventTypeIpChanged
	EventTypeSmartClusterQueueUpdateInfo
	EventTypeSmartClusterQueueActiveInfo
	EventTypeSmartClusterQueueKickWarning
	EventTypeSmartClusterQueueInvite
	EventTypeReceivedGvgSeasonPoints
	EventTypeTowerPowerPointUpdate
	EventTypeOpenWorldAttackScheduleStart
	EventTypeOpenWorldAttackScheduleFinished
	EventTypeOpenWorldAttackScheduleCancel
	EventTypeOpenWorldAttackConquerStart
	EventTypeOpenWorldAttackConquerFinished
	EventTypeOpenWorldAttackConquerCancel
	EventTypeOpenWorldAttackConquerStatus
	EventTypeOpenWorldAttackStart
	EventTypeOpenWorldAttackEnd
	EventTypeNewRandomResourceBlocker
	EventTypeNewHomeObject
	EventTypeHideoutObjectUpdate
	EventTypeUpdateInfamy
	EventTypeMinimapPositionMarkers
	EventTypeNewTunnelExit
	EventTypeCorruptedDungeonUpdate
	EventTypeCorruptedDungeonStatus
	EventTypeCorruptedDungeonInfamy
	EventTypeHellgateRestrictedAreaUpdate
	EventTypeHellgateInfamy
	EventTypeHellgateStatus
	EventTypeHellgateStatusUpdate
	EventTypeHellgateSuspense
	EventTypeReplaceSpellSlotWithMultiSpell
	EventTypeNewCorruptedShrine
	EventTypeUpdateCorruptedShrine
	EventTypeCorruptedShrineUsageStart
	EventTypeCorruptedShrineUsageCancel
	EventTypeExitUsed
	EventTypeLinkedToObject
	EventTypeLinkToObjectBroken
	EventTypeEstimatedMarketValueUpdate
	EventTypeStuckCancel
	EventTypeDungonEscapeReady
	EventTypeFactionWarfareClusterState
	EventTypeFactionWarfareHasUnclaimedWeeklyReportsEvent
	EventTypeSimpleFeedback
	EventTypeSmartClusterQueueSkipClusterError
	EventTypeXignCodeEvent
	EventTypeBatchUseItemStart
	EventTypeBatchUseItemEnd
	EventTypeRedZoneEventClusterStatus
	EventTypeRedZonePlayerNotification
	EventTypeRedZoneWorldEvent
	EventTypeFactionWarfareStats
	EventTypeUpdateFactionBalanceFactors
	EventTypeFactionEnlistmentChanged
	EventTypeUpdateFactionRank
	EventTypeFactionWarfareCampaignRewardsUnlocked
	EventTypeFeaturedFeatureUpdate
	EventTypeNewPowerCrystalObject
	EventTypeMinimapCrystalPositionMarker
	EventTypeCarryPowerCrystalUpdate
	EventTypePickupPowerCrystalStart
	EventTypePickupPowerCrystalCancel
	EventTypePickupPowerCrystalFinished
	EventTypeDoSimpleActionStart
	EventTypeDoSimpleActionCancel
	EventTypeDoSimpleActionFinished
	EventTypeNotifyGuestAccountVerified
	EventTypeMightAndFavorReceivedEvent //  map[0:63063 2:21021 3:16617 5:5539 6:349680 8:0 252:470] (0: Might, 2: Premium of might, 3: Favor, 5: Premium of favor, 6: Total favor, 8: ???)
	EventTypeWeeklyPvpChallengeRewardStateUpdate
	EventTypeNewUnlockedPvpSeasonChallengeRewards
	EventTypeStaticDungeonEntrancesDungeonEventStatusUpdates
	EventTypeStaticDungeonDungeonValueUpdate
	EventTypeStaticDungeonEntranceDungeonEventsAborted
	EventTypeInAppPurchaseConfirmedGooglePlay
	EventTypeFeatureSwitchInfo
	EventTypePartyJoinRequestAborted
	EventTypePartyInviteAborted
	EventTypePartyStartHuntRequest
	EventTypePartyStartHuntRequested
	EventTypePartyStartHuntRequestAnswer
	EventTypePartyPlayerLeaveScheduled
	EventTypeGuildInviteDeclined
	EventTypeCancelMultiSpellSlots
	EventTypeNewVisualEventObject
	EventTypeCastleClaimProgress
	EventTypeCastleClaimProgressLogo
	EventTypeTownPortalUpdateState
	EventTypeTownPortalFailed
	EventTypeConsumableVanityChargesAdded
	EventTypeFestivitiesUpdate
	EventTypeNewBannerObject
	EventTypeNewMistsImmediateReturnExit
	EventTypeMistsPlayerJoinedInfo
	EventTypeNewMistsStaticEntrance
	EventTypeNewMistsOpenWorldExit
	EventTypeNewTunnelExitTemp
	EventTypeNewMistsWispSpawn
	EventTypeMistsWispSpawnStateChange
	EventTypeNewMistsCityEntrance
	EventTypeNewMistsCityRoadsEntrance
	EventTypeMistsCityRoadsEntrancePartyStateUpdate
	EventTypeMistsCityRoadsEntranceClearStateForParty
	EventTypeMistsEntranceDataChanged
	EventTypeNewCagedObject
	EventTypeCagedObjectStateUpdated
	EventTypeMistsEntrancePartyBindingCreated
	EventTypeMistsEntrancePartyBindingCleared
	EventTypeMistsEntrancePartyBindingInfos
	EventTypeNewMistsBorderExit
	EventTypeNewMistsDungeonExit
	EventTypeLocalQuestInfos
	EventTypeLocalQuestStarted
	EventTypeLocalQuestActive
	EventTypeLocalQuestInactive
	EventTypeLocalQuestProgressUpdate
	EventTypeNewUnrestrictedPvpZone
	EventTypeTemporaryFlaggingStatusUpdate
	EventTypeSpellTestPerformanceUpdate
	EventTypeTransformation
	EventTypeTransformationEnd
	EventTypeUpdateTrustlevel
	EventTypeRevealHiddenTimeStamps
	EventTypeModifyItemTraitFinished
	EventTypeRerollItemTraitValueFinished
	EventTypeHuntQuestProgressInfo
	EventTypeHuntStarted
	EventTypeHuntFinished
	EventTypeHuntAborted
	EventTypeHuntMissionStepStateUpdate
	EventTypeNewHuntTrack
	EventTypeHuntMissionUpdate
	EventTypeHuntQuestMissionProgressUpdate
	EventTypeHuntTrackUsed
	EventTypeHuntTrackUseableAgain
	EventTypeMinimapHuntTrackMarkers
	EventTypeNoTracksFound
	EventTypeHuntQuestAborted
	EventTypeInteractWithTrackStart
	EventTypeInteractWithTrackCancel
	EventTypeInteractWithTrackFinished
	EventTypeNewDynamicCompound
	EventTypeLegendaryItemDestroyed
	EventTypeAttunementInfo //   map[0:T8_MAIN_AXE@4 1:0 2:180810 3:1000000000 252:554] 0: UniqueItemName, 2: GainedAttunement, 3: MaximalAttunementValue
	EventTypeTerritoryClaimRaidedRawEnergyCrystalResult
	EventTypeCarriedObjectExpiryWarning
	EventTypeCarriedObjectExpired
	EventTypeTerritoryRaidStart
	EventTypeTerritoryRaidCancel
	EventTypeTerritoryRaidFinished
	EventTypeTerritoryRaidResult
	EventTypeTerritoryMonolithActiveRaidStatus
	EventTypeTerritoryMonolithActiveRaidCancelled
	EventTypeMonolithEnergyStorageUpdate
	EventTypeMonolithNextScheduledOpenWorldAttackUpdate
	EventTypeMonolithProtectedBuildingsDamageReductionUpdate
	EventTypeNewBuildingBaseEvent
	EventTypeNewFortificationBuilding
	EventTypeNewCastleGateBuilding
	EventTypeBuildingDurabilityUpdate
	EventTypeMonolithFortificationPointsUpdate
	EventTypeFortificationBuildingUpgradeInfo
	EventTypeFortificationBuildingsDamageStateUpdate
	EventTypeSiegeNotificationEvent
	EventTypeUpdateEnemyWarBannerActive
	EventTypeTerritoryAnnouncePlayerEjection
	EventTypeCastleGateSwitchUseStarted
	EventTypeCastleGateSwitchUseFinished
	EventTypeFortificationBuildingWillDowngrade
	EventTypeBotCommand
	EventTypeJournalAchievementProgressUpdate
	EventTypeJournalClaimableRewardUpdate
	EventTypeKeySync
	EventTypeLocalQuestAreaGone
	EventTypeDynamicTemplate
	EventTypeDynamicTemplateForcedStateChange
	EventTypeNewOutlandsTeleportationPortal
	EventTypeNewOutlandsTeleportationReturnPortal
	EventTypeOutlandsTeleportationBindingCleared
	EventTypeOutlandsTeleportationReturnPortalUpdateEvent
	EventTypePlayerUsedOutlandsTeleportationPortal
	EventTypeEncumberedRestricted
	EventTypeNewPiledObject
	EventTypePiledObjectStateChanged
	EventTypeNewSmugglerCrateDeliveryStation
	EventTypeKillRewardedNoFame
	EventTypePickupFromPiledObjectStart
	EventTypePickupFromPiledObjectCancel
	EventTypePickupFromPiledObjectReset
	EventTypePickupFromPiledObjectFinished
	EventTypeArmoryActivityChange
	EventTypeNewKillTrophyFurnitureBuilding
)
